version: '3'

services:
            endlessh:
                image: lscr.io/linuxserver/endlessh:latest
                container_name: endlessh
                environment:
                    - PUID=1000
                    - PGID=1000
                    - TZ=Etc/UTC
                ports:
                    - 22:2222
                restart: unless-stopped
        
            reverse_proxy:
                image: nginx:alpine
                container_name: reverse_proxy
                ports:
                    - 443:443
                volumes:
                    - ./nginx/reverse.conf:/etc/nginx/conf.d/default.conf:ro
                    - ./nginx/server.crt:/root/ssl/server.crt
                    - ./nginx/server.key:/root/ssl/server.key
                depends_on:
                  - nginx
            nginx:
                image: nginx:alpine
                container_name: nginx
                volumes:
                    - ./nginx/index.html:/usr/share/nginx/html/index.html