version: '3.8'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./web:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: docker_database
      DB_USER: root
      DB_PASSWORD: password
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_database
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
